//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace webBanCayTrong.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DonGiao
    {
        public int MaDH { get; set; }
        public Nullable<int> MaShipper { get; set; }
        public Nullable<System.DateTime> NgayGiao { get; set; }
        public string TrangThai { get; set; }
        public Nullable<System.DateTime> NgayNhanHang { get; set; }
        public string GhiChu { get; set; }
    
        public virtual DonHang DonHang { get; set; }
        public virtual Shipper Shipper { get; set; }
    }
}
