//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace webBanCayTrong.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Email
    {
        public int MaEmail { get; set; }
        public string Email1 { get; set; }
    }
}
