//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace webBanCayTrong.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class SanPham
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SanPham()
        {
            this.DanhGias = new HashSet<DanhGia>();
            this.DonHangs = new HashSet<DonHang>();
        }
        
        [Display(Name = "Mã sản phẩm:")]
        public int MaSP { get; set; }

        [Display(Name = "Tên sản phẩm:")]
        [Required(ErrorMessage = "Vui lòng nhập tên sản phẩm")]
        public string TenSP { get; set; }

        [Display(Name = "Số lượng:")]
        public Nullable<int> SoLuong { get; set; }

        [Display(Name = "Số lượng nhập:")]
        [Required(ErrorMessage = "Vui lòng nhập số lượng nhập")]
        public Nullable<int> SLNhap { get; set; }

        public Nullable<float> SoSao { get; set; }

        [Display(Name = "Mô tả 1:")]
        public string MoTa1 { get; set; }

        [Display(Name = "Mô tả 2:")]
        public string MoTa2 { get; set; }

        public string Img1 { get; set; }
        public string Img2 { get; set; }
        public string Img3 { get; set; }
        public Nullable<int> MaLoai { get; set; }
        public Nullable<int> MaDanhMuc { get; set; }
        public Nullable<int> SLDaBan { get; set; }

        [Display(Name = "Giá bán:")]
        [Required(ErrorMessage = "Vui lòng nhập giá bán")]
        public Nullable<int> GiaBan { get; set; }

        [Display(Name = "Giá nhập:")]
        [Required(ErrorMessage = "Vui lòng nhập giá nhập:")]
        public Nullable<int> GiaNhap { get; set; }
    
        public virtual DanhMuc DanhMuc { get; set; }
        public virtual LoaiCay LoaiCay { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DanhGia> DanhGias { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DonHang> DonHangs { get; set; }
    }
}
